@startuml

start

:Declare variables for Divident, Divisor, Quotient and Remainder;
:Get Divident, Divisor from user;
:Quotient <- Divident / Divisor
Remainder <- Dividend % Divisor;
:Display Quotient and Remainder;
end

@enduml